### PR TITLE
New internal pid filtering functionality

### PR DESCRIPTION
**Pull request by lars18th**
New implementation of internal pid filtering.
This is added to the Child PIPE input. But some generic code is refactored for reusability.

### CODE REVIEW

**Comment by lars18th** [comment]
Hi @Barracuda09 ,

This is my final implementation of the internal pid filtering. It's for Child PIPE input, but it has some generic code to port it to other inputs. Here a guide to add support for it:
- In the concrete DeviceData subclass you need to rewrite the virtual function `capableOfInternalFiltering()` returning TRUE to enable the UI and control it with the member `_internalPidFiltering`.
- In the concrete Device subclass add two private functions `updatePIDFilters()` and `closeActivePIDFilters()`. They can call to the generic `dummyUpdatePIDFilters()` and `dummyCloseActivePIDFilters()`.
- In the concrete DeviceData subclass call to the function `updatePidsTable(params)` when corresponds inside `doParseStreamString()`.
- In the concrete Device subclass call to `closeActivePIDFilters()` and `updatePIDFilters()` (described above) when corresponds inside `update()` and `teardown()`.
- Finally change the code of concrete `Device::readFullTSPacket()` to enable the filtering when calling to `getFilterData()`. Withtout changes the code continues to work as expected until now. Adding a new parameter to enable the filtering, with the previous changes the Buffer will be automatically purged removing the unused pids. Be advised that you can do two things to handle the purge of the buffer. The first option is to use the new function `mpegts::PacketBuffer::markToFlush()` to pass to the upper layer the Buffer as a valid even it has less TS packets. The second option is to read in a loop until the Buffer is full. The implementation for the Child PIPE input use both options.

A last comment is that I've considered all of your suggestions. Thank you for them. I used all expect one: The PURGE of the Buffer is mandatory. The reason is for efficiency. As the filtering is done _after_ reading in the buffer, we need to purge it. And copy data to another Buffer is a bad solution. Futhermore, to purge correctly the buffer and do the minimum number of "memmove()" calls I've implemented an optimal algorithm. So only minimum tasks are done. Perhaps the code is a bit more complex. But all is encapsulated and nothing changes. You only need to handle that a call to `Filter::addData(FeID, Buffer, true)` could change the Buffer. And then you need to flush it or add more data.

Please check it. 😉

**Comment by Barracuda09** [comment]
Hi @lars18th 

Thanks for you PR!

I have to check the code beter, but what are these functions for
`dummyUpdatePIDFilters()` and `dummyCloseActivePIDFilters()` the name suggets that it is not realy needed or has this an other meaning?

**Comment by lars18th** [comment]
Hi @Barracuda09 ,

> I have to check the code beter, but what are these functions for
dummyUpdatePIDFilters() and dummyCloseActivePIDFilters() the name suggets that it is not realy needed or has this an other meaning?

Yes, these functions are really "dummy" inside the `DeviceData` base class. The implementation only calls to `closeActivePIDFilters()` and `updatePIDFilters()` template functions declared in `Filter.h`. The call is done using Lambda functions. To the best of my knowledge, what these functions do actually do is refresh the internal list of pids of the Filter class, and they have a callback to invoke when there is a change in the pid list. Therefore, the functions must exist because otherwise the pid list are not updated. And then the implementation is generic with a _dummy_ callback. Finally, in my code the call to these two _dummy_ functions are done inside the concrete implementation of the `TSReader::updatePIDFilters()` and `TSReader::closeActivePIDFilters()`.

If the funcitonality is different (you have implemented it), then please comment it. What about the rest of the code?

**Comment by Barracuda09** [comment]
Hi @lars18th 

Your code looks good, but a few pointers:

- About the `dummyUpdatePIDFilters()` and `dummyCloseActivePIDFilters()`, I think they can be moved.
And can be move `void updatePIDFilters()` and `void closeActivePIDFilters()` from `Frontend` class to base class `Device` and make them virtual. So these in the base class you can implement the 'dummy' that does only what you have in your patch. and in Frontend class will remain the same, but move it in header file and make it virtual as well.
- The `updatePIDFilters();` should be called only from a Device class so not from DeviceData class (See Frontend class)
- The `bool markToFlush()` what is real the use for this? why not read in more data to fill it?
  I do understand the intention, but the name is confusing to me. And makes me think to flush/remove it, but it will be send.
  But this is more a matter of taste.

**Comment by lars18th** [comment]
Hi @Barracuda09 ,

> Your code looks good,

I'm glad you agree with the code. 😉 

> but a few pointers:

I'll try to explain them:

> The bool markToFlush() what is real the use for this? why not read in more data to fill it?
I do understand the intention, but the name is confusing to me. And makes me think to flush/remove it, but it will be send.
But this is more a matter of taste.

This function has the objective of _enforce to send the buffer even if it's not full (actually 7 TS packets)_. The reason is the function `PacketBuffer::isReadyToSend()` used here: https://github.com/Barracuda09/SATPI/blob/c4077cab8048d211d8b7181a9da05f5d1fc61409/src/output/StreamThreadBase.cpp#L226-L227 Without the added `PacketBuffer::_flushable` member it's imposible to write out the data of small buffers. And my solution is to add this _optional_ function `markToFlush()` to mark a Buffer as _valid to send_. You can use this function when you want: 1) Flush a buffer when it has less than 7 packets (typically because a timeout). Or 2) when you want to read-filter-send without rereading (suboptimal but easy). If you prefer to change the name of this function, then you can do it after merging it.

> About the dummyUpdatePIDFilters() and dummyCloseActivePIDFilters(), I think they can be moved.

Today these functions are used only by the Child PIPE input. However, I'll promote then to all inputs. And because at time only the real DVB tuners require a different functions. So, why remove them?

> And can be move void updatePIDFilters() and void closeActivePIDFilters() from Frontend class to base class Device and make them virtual. 

My original idea has to put them in the Device class, but that's impossible. The problem is that the call is to `Filter::updatePIDFilters()` in this template https://github.com/Barracuda09/SATPI/blob/0382989bfa4663f48924b0c76c1eef9c0700a02e/src/mpegts/Filter.h#L126-L127
So we need the Filter object. And the Filter object is only present inside the DeviceData and not the Frontend: https://github.com/Barracuda09/SATPI/blob/0b533820131fe91784fb70ffb1ba3bc6f2743c3f/src/input/DeviceData.h#L141
Then my solution is to implement the concrete functions in the Frontend subclass and call from here to the "dummy" (or generic) functions through the `_deviceData` member inside the concrete subclass derived from Device. If you have a best alternative, please let me know it.

> The updatePIDFilters(); should be called only from a Device class so not from DeviceData class (See Frontend class)

This is the same as the previous, right? Without the `Filter` object we can't define lambda function that calls to the `Filter::updatePIDFilters()`. Or I'm missing something?

I'm impatient for merging this PR. The reason is becuase I want to add the funcitonality to other inputs. And after enhance the code with  external pid filtering support (sending commands to the child process with the list of pids when a change in the list is completed). Therefore if you want perhaps you can merge it and change some parts after. You agree?

**Comment by Barracuda09** [comment]
@lars18th 

Have merged your pull, have made a few changes.

**Pull request merged**
