### PR TITLE
Add support for systemd and to package satpi to ubuntu or debian packages.

### PR DESCRIPTION
**Pull request by MHoyer12345678**
Hello,
I'm using satpi in my mediaserver, cool sw ;) I extended it a bit to create a debian package out of it. If you are interested, feel free to take over the changes:
- I added an install and uninstall section (installing binary, web folder, systemd service file; create data folder) 
- I added a systemd service file that starts satpi with command line options pointing to the web and data folder created in the install section
- I added a debian control file easily allowing people to create debian packages
* rename the folder with satpi inside to satpi-<v.v.v>
* cd into the folder
* call `dh_make -s --createorig -a` to creating version and maintainer specific files for the package
- adapt the files created
- call `dpkg-build -uc -us`
- source, debug, and binary packages are created above the satpi-<v.v.v> folder.

Hope the helps. If you need adaptions, let me know ...

Regards,
Marko

### CODE REVIEW

**Comment by Barracuda09** [comment]
Hi Marko,

Thanks for your interest and contribution to SatPI. I will lock at it, in more detail, tomorrow.

Kind regards,

Marc

**Review by Barracuda09 — CHANGES_REQUESTED** [review]
Hi Marko,

I am no expert in systemd service files, but have some change requests:
- maybe add `After=network-online.target` to ensure the network is running
- maybe add `Restart=always` to ensure on crash it will restart automatically 

What do you think about adding this?

Regards,
Marc

**Comment by MHoyer12345678** [comment]
Mmm. I'm a bit of a beginner using PRs. Hope everything went right.
I added the synchronization to network-online.target even though this is not needed in most distributions startup configuration since network setup conventionally is part of basic.target which is a default dependency of all units ... Anyway, this is now the safe way.
I also added the restart line and tested it. Works as expected.

Regards,
Marko

**Review by Barracuda09 — APPROVED** [review]
This looks ok. Thanks @MHoyer12345678 , for you contribution.

**Pull request merged**
